theme = "onedark"

# true-color = true
# icons = "nerd"

[keys.normal]
# use `li` or remap `after insert`
a = ["move_char_right", "insert_mode"]
"C-s" = ":write"                       # 原保存跳转列表位置，修改为 C-j
"C-j" = ["save_selection"]
"C-r" = ":reload"
# "C-z" = "normal_mode"                  # replace suspend
# "C-q" = ":quit"
"A-/" = "toggle_comments"
"\\" = ":reflow"                       # |
# "X" = "extend_line_above"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode




[editor]
# 真彩支持
# 使用 infocmp | rg color 检查是否支持 256color [终端控制命令 infocmp](http://manual.51yip.com/shell/terminalccmds.html) 
# 使用 tmux 的时候,追加配置  
# set -g default-terminal "tmux-256color" 
# set -ga terminal-overrides ',xterm-256color:Tc' 
# 需要 export TERM=xterm-256color  
# tty export COLORTERM=truecolor
true-color = true

auto-completion = true
# auto-save = false
auto-info = true
# cursorcolumn = true # 光标列高亮
cursorline = true  # 光标 行高亮
color-modes = true
idle-timeout = 40
# mouse = true
# scrolloff = 5 # 滚动时上下边缘填充行数
# scroll-lines = 3
# line-number = "relative"  # 行号类型 absolute / relative 
# rulers = [80, 120]   # 标尺

bufferline = "multiple"  # always | multiple | nerver
# gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

# [editor.lsp]
# # 服务器语言信息提示 
# display-messages = true
# # display-signature-help-docs = false
# # LSP Type Hints default is false
# display-inlay-hints = true
#
# # [editor.whitespace]
# # render = "all"
#
#

